sudo: false
script: script/test
rvm:
  - 1.9.3
  - '2.1'
  - '2.2'
  - 2.3.0
notifications:
  email: false
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T4UMAMTHC'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
